services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      apt-get update && apt-get install -y graphviz
      pip install -r requirements.txt
    startCommand: gunicorn Website.main:app